spring:
  profiles:
    active: prod

  web:
    resources:
      add-mappings: false

  datasource:
    master:
      hikari:
        url: ${spring.datasource.master.hikari.jdbc-url}
        username: ${spring.datasource.master.hikari.username}
        password: ${spring.datasource.master.hikari.password}
        driver-class-name: ${spring.datasource.master.hikari.driver-class-name}
        maximum-pool-size: 55   # 최대 커넥션 개수
        minimum-idle: 20         # 최소 유휴 커넥션 개수
        idle-timeout: 30000     # 커넥션 유휴 타임아웃 (밀리초, 기본값 600000ms = 10분)
        max-lifetime: 180000    # 커넥션 최대 생명주기 (밀리초, 기본값 1800000ms = 30분)
        connection-timeout: 30000 # 커넥션 획득 타임아웃 (밀리초, 기본값 30000ms = 30초)
    slave:
      hikari:
        url: ${spring.datasource.slave.hikari.jdbc-url}
        username: ${spring.datasource.slave.hikari.username}
        password: ${spring.datasource.slave.hikari.password}
        driver-class-name: ${spring.datasource.slave.hikari.driver-class-name}
        maximum-pool-size: 75   # 최대 커넥션 개수
        minimum-idle: 20         # 최소 유휴 커넥션 개수
        idle-timeout: 30000     # 커넥션 유휴 타임아웃 (밀리초, 기본값 600000ms = 10분)
        max-lifetime: 180000    # 커넥션 최대 생명주기 (밀리초, 기본값 1800000ms = 30분)
        connection-timeout: 30000 # 커넥션 획득 타임아웃 (밀리초, 기본값 30000ms = 30초)

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        id:
          new_generator_mappings: true
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
        format_sql: true
    open-in-view: false

  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.engine.jdbc.batch.internal: DEBUG

server:
  tomcat:
    mbeanregistry:
      enabled: true # 메트릭 확인
    threads:
      max: 200          # 최대 스레드 수 (maximumPoolSize)
      min-spare: 100     # 최소 대기 스레드 수 (corePoolSize와 비슷)
    accept-count: 1000     # 대기 큐 용량 (ArrayBlockingQueue와 유사)
  error:
    include-message: always # message 정보를 항상 포함
    include-binding-errors: always # 바인딩 에러 포함 여부
    include-stacktrace: never # 스택트레이스를 숨기거나 표시

#Hibernate가 실행하는 모든 작업을 자세히 기록
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG # Hibernate SQL 로그 활성화
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE # SQL 파라미터 바인딩 로그 출력

jwt:
  secret: ${jwt.secret}

token:
  expire:
    time:
      access: ${token.expire.time.access}
      refresh: ${token.expire.time.refresh}

springdoc:
  packages-to-scan: com.example
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    tags-sorter: method
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

myapp:
  local-url: ${myapp.local-url}

management:
  endpoints:
    web:
      exposure:
        include: "*"